java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseZGC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java
java -XX:+UseG1GC GenerationalZGarbageCollector.java